In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.drop(["deck","embark_town","alive","class","who","adult_male"] , axis=1 , inplace =True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
df["age"].fillna(df["age"].mean(),inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
df['sex']= le.fit_transform((df['sex']))
df["embarked"]= le.fit_transform(df["embarked"]) #S=2 , C=0 , Q=0

In [ ]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [ ]:
df= df.astype(int)

In [ ]:
X =  df.drop("survived",axis=1)
y=df["survived"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred =model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [ ]:
accuracy_score(y_test,y_pred)

0.7988826815642458

In [ ]:
confusion_matrix(y_test,y_pred)

array([[89, 16],
       [20, 54]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [ ]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[891 rows x 9 columns]

In [ ]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
331       1    1   45      0      0    28         2      1
733       2    1   23      0      0    13         2      1
382       3    1   32      0      0     7         2      1
704       3    1   26      1      0     7         2      0
813       3    0    6      4      2    31         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
106       3    0   21      0      0     7         2      1
270       1    1   29      0      0    31         2      1
860       3    1   41      2      0    14         2      0
435       1    0   14      1      2   120         2      0
102       1    1   21      0      1    77         2      0

[712 rows x 8 columns]

In [ ]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
709       3    1   29      1      1    15         0      0
439       2    1   31      0      0    10         2      1
840       3    1   20      0      0     7         2      1
720       2    0    6      0      1    33         2      0
39        3    0   14      1      0    11         0      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
773       3    1   29      0      0     7         0      1
25        3    0   38      1      5    31         2      0
84        2    0   17      0      0    10         2      1
10        3    0    4      1      1    16         2      0

[179 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [ ]:
X_train_scaled

array([[-1.61413602,  0.7243102 ,  1.20171344, ..., -0.08024759,
         0.55744438,  0.81220297],
       [-0.40055118,  0.7243102 , -0.49136439, ..., -0.36900912,
         0.55744438,  0.81220297],
       [ 0.81303367,  0.7243102 ,  0.20125836, ..., -0.48451374,
         0.55744438,  0.81220297],
       ...,
       [ 0.81303367,  0.7243102 ,  0.89388111, ..., -0.34975835,
         0.55744438, -1.23121934],
       [-1.61413602, -1.38062393, -1.18398714, ...,  1.69082316,
         0.55744438, -1.23121934],
       [-1.61413602,  0.7243102 , -0.64528056, ...,  0.86304009,
         0.55744438, -1.23121934]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn =knn_model.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_knn)

0.8100558659217877

In [ ]:
confusion_matrix(y_test,y_pred_knn)

array([[93, 12],
       [22, 52]])

In [ ]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.81      0.89      0.85       105
           1       0.81      0.70      0.75        74

    accuracy                           0.81       179
   macro avg       0.81      0.79      0.80       179
weighted avg       0.81      0.81      0.81       179

In [70]:
from sklearn.svm import SVC

In [72]:
model_svm = SVC(kernel='rbf')

In [73]:
model_svm.fit(X_train_scaled, y_train)

SVC()

In [75]:
y_pred_svc = model_svm.predict(X_test_scaled)

In [76]:
accuracy_score(y_test,y_pred_svc)

0.8100558659217877

In [79]:
confusion_matrix(y_test,y_pred_svc)

array([[93, 12],
       [22, 52]])